services:
  app:
    build: .
    container_name: property-rental-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://ep-dawn-hall-a1ti7go7-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require"
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_21hBWcMoNAjP
      # Automatically create/update database tables
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Useful for debugging connection issues
      SPRING_JPA_SHOW_SQL: "true"
    restart: always